import type { Metadata } from "next";

import { PublicFooter } from "@/components/public-footer";
import { PublicHeader } from "@/components/public-header";
import { copy, getRequestLocale } from "@/lib/i18n";

export const metadata: Metadata = { title: "Privacy" };

export default async function PrivacyPage() {
  const locale = await getRequestLocale();
  return (
    <>
      <PublicHeader locale={locale} returnTo="/privacy" />
      <main id="main-content" className="page-shell legal-page">
        <p className="eyebrow">{copy(locale, { en: "Privacy", ml: "സ്വകാര്യത" })}</p>
        <h1>{copy(locale, { en: "Only the information needed for learning support", ml: "പഠനപിന്തുണയ്ക്ക് ആവശ്യമായ വിവരങ്ങൾ മാത്രം" })}</h1>
        <p>{copy(locale, { en: "Kanni stores school accounts, role memberships, approved teacher-student and parent-student links, curriculum packs, learning-studio records, language preferences, and security audit events in PostgreSQL.", ml: "സ്കൂൾ അക്കൗണ്ടുകൾ, ചുമതല അംഗത്വങ്ങൾ, അംഗീകരിച്ച അധ്യാപക-വിദ്യാർത്ഥി, രക്ഷിതാവ്-വിദ്യാർത്ഥി ബന്ധങ്ങൾ, പാഠ്യപദ്ധതി പാക്കുകൾ, പഠന സ്റ്റുഡിയോ രേഖകൾ, ഭാഷാ മുൻഗണനകൾ, സുരക്ഷാ ഓഡിറ്റ് സംഭവങ്ങൾ എന്നിവ കണ്ണി PostgreSQL-ൽ സൂക്ഷിക്കുന്നു." })}</p>
        <section><h2>{copy(locale, { en: "Account and session data", ml: "അക്കൗണ്ടും സെഷൻ വിവരങ്ങളും" })}</h2><p>{copy(locale, { en: "Passwords are stored as bcrypt hashes. The browser receives an HttpOnly session cookie. Server sessions expire and can be revoked. Login throttling keys are hashed before storage.", ml: "പാസ്‌വേഡുകൾ bcrypt ഹാഷുകളായി സൂക്ഷിക്കുന്നു. ബ്രൗസറിന് HttpOnly സെഷൻ കുക്കി ലഭിക്കുന്നു. സെഷനുകൾ കാലഹരണപ്പെടുകയും പിൻവലിക്കാനാകുകയും ചെയ്യും. ലോഗിൻ നിയന്ത്രണ കീകൾ സൂക്ഷിക്കുന്നതിന് മുമ്പ് ഹാഷ് ചെയ്യുന്നു." })}</p></section>
        <section><h2>{copy(locale, { en: "Learning records", ml: "പഠന രേഖകൾ" })}</h2><p>{copy(locale, { en: "A learning studio records the learner's chosen route, prediction, first version, self-critique, revision, explanation, reflection, and whether support was opened. Only the learner and assigned teacher can read this raw work. Parents receive a short teacher-written observation and home activity. School administrators receive workflow status, not the submission.", ml: "പഠന സ്റ്റുഡിയോയിൽ പഠിതാവ് തിരഞ്ഞെടുത്ത വഴി, പ്രവചനം, ആദ്യ രൂപം, സ്വയം വിമർശനം, തിരുത്തൽ, വിശദീകരണം, പ്രതിഫലനം, പിന്തുണ തുറന്നോ എന്ന വിവരം എന്നിവ രേഖപ്പെടുത്തുന്നു. പഠിതാവിനും നിയുക്ത അധ്യാപകനും മാത്രം ഈ അസംസ്കൃത പ്രവർത്തി വായിക്കാം. രക്ഷിതാവിന് അധ്യാപകൻ എഴുതിയ ചെറിയ നിരീക്ഷണവും വീട്ടുപ്രവർത്തനവും ലഭിക്കുന്നു. സ്കൂൾ അഡ്മിനിസ്ട്രേറ്റർക്ക് പ്രവർത്തനനില മാത്രം ലഭിക്കുന്നു, സമർപ്പണം ലഭിക്കില്ല." })}</p></section>
        <section><h2>{copy(locale, { en: "Optional AI support", ml: "ഐച്ഛിക AI പിന്തുണ" })}</h2><p>{copy(locale, { en: "AI is off unless the school operator configures OpenRouter and confirms external rate and spend controls. Teacher planning and student help are separate, explicit requests. Student help has a separate switch that remains off until the operator reviews external student-data processing, and every request requires an adult to confirm that they are testing the feature or supervising the activity. A teacher plan sends the teacher-written goal, driving question, class, and up to six retrieved curriculum sections. Student help is available only after a first attempt and sends that attempt with up to four relevant sections so the model can return questions and small experiments, not a finished answer. Kanni does not add account names, family notes, passwords, other submission fields, or earlier model conversations. Kanni asks OpenRouter to exclude providers that collect request data and sets store to false. Current GPT-5.6 routes do not offer Zero Data Retention, so external safety-monitoring retention may still apply. Unsafe output, answer-revealing text, or an unknown source ID is hidden in full.", ml: "സ്കൂൾ ഓപ്പറേറ്റർ OpenRouter ക്രമീകരിച്ച് ബാഹ്യ അഭ്യർത്ഥനയും ചെലവ് നിയന്ത്രണങ്ങളും സ്ഥിരീകരിക്കുന്നതുവരെ AI ഓഫായിരിക്കും. അധ്യാപക ആസൂത്രണവും വിദ്യാർത്ഥി സഹായവും വേർതിരിച്ച, വ്യക്തമായി ആവശ്യപ്പെടുന്ന പ്രവർത്തനങ്ങളാണ്. ബാഹ്യ വിദ്യാർത്ഥി ഡാറ്റ പ്രോസസ്സിംഗ് ഓപ്പറേറ്റർ പരിശോധിക്കുന്നതുവരെ വിദ്യാർത്ഥി സഹായത്തിനുള്ള പ്രത്യേക സ്വിച്ച് ഓഫായിരിക്കും. ഓരോ അഭ്യർത്ഥനയ്ക്കും 18 വയസ്സ് തികഞ്ഞ ഒരാൾ താനാണ് പരീക്ഷിക്കുന്നതെന്നോ പ്രവർത്തനത്തിന് മേൽനോട്ടം വഹിക്കുന്നതെന്നോ സ്ഥിരീകരിക്കണം. അധ്യാപക ആസൂത്രണത്തിന് പഠനലക്ഷ്യം, പ്രധാന ചോദ്യം, ക്ലാസ്, പ്രസക്തമായ പരമാവധി ആറു പാഠ്യപദ്ധതി വിഭാഗങ്ങൾ എന്നിവ അയക്കും. വിദ്യാർത്ഥി ആദ്യം സ്വന്തം ശ്രമം എഴുതിയതിന് ശേഷം മാത്രമേ AI സഹായം ലഭിക്കൂ. ആ ശ്രമവും പ്രസക്തമായ പരമാവധി നാല് വിഭാഗങ്ങളും അയച്ച് ചോദ്യങ്ങളും ചെറിയ പരീക്ഷണങ്ങളും മാത്രം ലഭിക്കും, പൂർത്തിയായ ഉത്തരം ലഭിക്കില്ല. അക്കൗണ്ട് പേരുകൾ, കുടുംബ കുറിപ്പുകൾ, പാസ്‌വേഡുകൾ, സമർപ്പണത്തിലെ മറ്റ് ഭാഗങ്ങൾ, മുൻ സംഭാഷണങ്ങൾ എന്നിവ കണ്ണി ചേർക്കില്ല. അഭ്യർത്ഥനാ വിവരങ്ങൾ ശേഖരിക്കുന്ന ദാതാക്കളെ ഒഴിവാക്കാനും വിവരങ്ങൾ സംഭരിക്കാതിരിക്കാനും കണ്ണി OpenRouter-നോട് ആവശ്യപ്പെടുന്നു. നിലവിലെ GPT-5.6 വഴികളിൽ Zero Data Retention ലഭ്യമല്ല, അതിനാൽ ബാഹ്യ സുരക്ഷാ പരിശോധനാ നിലനിർത്തൽ ബാധകമായേക്കാം. സുരക്ഷിതമല്ലാത്ത ഫലമോ ഉത്തരം വെളിപ്പെടുത്തുന്ന വാചകമോ പരിചയമില്ലാത്ത ഉറവിട ഐഡിയോ വന്നാൽ മുഴുവൻ ഫലവും മറയ്ക്കും." })}</p></section>
        <section><h2>{copy(locale, { en: "School responsibility", ml: "സ്കൂളിന്റെ ഉത്തരവാദിത്തം" })}</h2><p>{copy(locale, { en: "A school must set its retention period, obtain the permissions required in its jurisdiction, review who can access each learner, and provide a contact for corrections or deletion requests before using Kanni with real student data.", ml: "യഥാർത്ഥ വിദ്യാർത്ഥി വിവരങ്ങളുമായി കണ്ണി ഉപയോഗിക്കുന്നതിന് മുമ്പ് സ്കൂൾ നിലനിർത്തൽ കാലയളവ് നിശ്ചയിക്കുകയും ആവശ്യമായ അനുമതികൾ നേടുകയും ഓരോ പഠിതാവിനെയും ആരെല്ലാം കാണാമെന്ന് പരിശോധിക്കുകയും തിരുത്തൽ അല്ലെങ്കിൽ മായ്ക്കൽ അഭ്യർത്ഥനകൾക്കായി ബന്ധപ്പെടാനുള്ള മാർഗം നൽകുകയും വേണം." })}</p></section>
      </main>
      <PublicFooter locale={locale} />
    </>
  );
}
